services:
  dev:
    build: .
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/src
    working_dir: /src
    ports:
      - "8080:8080"
    stdin_open: true # Keeps the standard input open
    tty: true        # Keeps the terminal session "alive"
    # Option A: Just use bash (manually run cmake/make once inside)
    command: bash